services:
  db:
    image: postgres:14.7-bullseye
    restart: always
    env_file:
      - ".env"
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - "./pgdata:/var/lib/postgresql/data"

volumes:
  db: {}
