# fly.toml app configuration file generated for frolfr-server on 2023-04-23T12:58:51-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "frolfr-server"
primary_region = "iad"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"
