#!/usr/bin/env bash

# script/server: launch to application and any extra required processes locally

set -e

cd "$(dirname "$0")/.."

# ensure everything in the app is up to date.
script/setup

test -z "$RACK_ENV" &&
    RACK_ENV="development"

rm -f tmp/pids

unset -v TERM

exec bundle exec unicorn -c config/unicorn.rb -E $RACK_ENV; 